services:
  backend:
    image: ghcr.io/kukaraf/osmosis_language_learning:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - db-data:/app/data
    environment:
      DATABASE_URL: "sqlite+aiosqlite:////app/data/osmosis.db"

volumes:
  db-data:
