"""initial

Revision ID: bc2c99d5a8e8
Revises: 
Create Date: 2026-03-11 20:21:02.239104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2c99d5a8e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.Text(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('decay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('oidc_sub', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('known_languages', sa.Text(), nullable=True),
    sa.Column('target_language', sa.Text(), nullable=True),
    sa.Column('daily_token_limit', sa.Integer(), nullable=False),
    sa.Column('tokens_used_today', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_groomed_at', sa.Text(), nullable=True),
    sa.Column('payment_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_sub')
    )
    op.create_index('idx_users_oidc_sub', 'users', ['oidc_sub'], unique=False)
    op.create_table('cats',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('hospitalized_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cats_user_lang', 'cats', ['user_id', 'language'], unique=True)
    op.create_table('commune_billing',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('commune_id', sa.Text(), nullable=False),
    sa.Column('billing_month', sa.Text(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('total_llm_cost', sa.Float(), nullable=False),
    sa.Column('price_per_user', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['commune_id'], ['communes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commune_billing', 'commune_billing', ['commune_id', 'billing_month'], unique=True)
    op.create_table('commune_members',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('commune_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['commune_id'], ['communes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_commune_members_commune', 'commune_members', ['commune_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('known_words', sa.Integer(), nullable=True),
    sa.Column('srt_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_user', 'goals', ['user_id', 'status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_table('srs_cards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('card_type', sa.Text(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('fsrs_stability', sa.Float(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_due', sa.Text(), nullable=True),
    sa.Column('fsrs_last_review', sa.Text(), nullable=True),
    sa.Column('fsrs_reps', sa.Integer(), nullable=False),
    sa.Column('fsrs_lapses', sa.Integer(), nullable=False),
    sa.Column('fsrs_state', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_srs_user_due', 'srs_cards', ['user_id', 'language', 'fsrs_due'], unique=False)
    op.create_table('token_transactions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_payment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_tx_user', 'token_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('cat_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_user', 'conversations', ['user_id'], unique=False)
    op.create_table('srs_review_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('scheduled_days', sa.Float(), nullable=True),
    sa.Column('elapsed_days', sa.Float(), nullable=True),
    sa.Column('review_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['srs_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_logs_card', 'srs_review_logs', ['card_id', 'review_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_review_logs_card', table_name='srs_review_logs')
    op.drop_table('srs_review_logs')
    op.drop_index('idx_conversations_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_token_tx_user', table_name='token_transactions')
    op.drop_table('token_transactions')
    op.drop_index('idx_srs_user_due', table_name='srs_cards')
    op.drop_table('srs_cards')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_goals_user', table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_commune_members_commune', table_name='commune_members')
    op.drop_table('commune_members')
    op.drop_index('idx_commune_billing', table_name='commune_billing')
    op.drop_table('commune_billing')
    op.drop_index('idx_cats_user_lang', table_name='cats')
    op.drop_table('cats')
    op.drop_index('idx_users_oidc_sub', table_name='users')
    op.drop_table('users')
    op.drop_table('communes')
    # ### end Alembic commands ###
